services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_RELOAD: "true"
    # No volumes if using remote daemon
